import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
// import { store } from "./redux/store";
// import { Provider } from 'react-redux'
// import { useContext } from "react";

const inter = Inter({ subsets: ["latin"] });

// for context of user authentication
// const AuthContext = useContext();

export const metadata = {
  title: "Developer Blogs",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} absolute top-0 z-[-2] h-screen w-screen bg-neutral-950 bg-[radial-gradient(ellipse_80%_80%_at_50%_-20%,rgba(120,119,198,0.3),rgba(255,255,255,0))]`}>
        
        {/* <Provider store={store}> */}
          <Navbar />
          {children}
        {/* </Provider> */}

      </body>
    </html>
  );
}
